quarkus.http.port=8180
quarkus.langchain4j.openai.base-url=http://localhost:8080/v1/
quarkus.langchain4j.openai.timeout=5m
quarkus.langchain4j.openai.chat-model.log-requests = true

# JDBC MCP Configuration
quarkus.langchain4j.mcp.todo-db.transport-type=stdio
quarkus.langchain4j.mcp.todo-db.command=jbang,jdbc@quarkiverse/quarkus-mcp-servers,jdbc:sqlite:todo.sqlite

# Register this very same application as a MCP Server
quarkus.langchain4j.mcp.internal-tools.transport-type=streamable-http
quarkus.langchain4j.mcp.internal-tools.url=http://localhost:8180/mcp/
